name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Dependencies
      run: npm ci --ignore-scripts
    - name: Build
      run: npm run build
    - name: Check
      run: npm run check
